export const OBTENER_INTEGRANTES = 'OBTENER_INTEGRANTES';
export const INTEGRANTE_ERROR = 'INTEGRANTE_ERROR';

export const OBTENER_ALBUMES = 'OBTENER_ALBUMES';
export const ALBUM_ERROR = 'ALBUM_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';