export const OBTENER_INTEGRANTES = 'OBTENER_INTEGRANTES';
export const INTEGRANTE_ERROR = 'INTEGRANTE_ERROR';

export const OBTENER_ALBUMES = 'OBTENER_ALBUMES';
export const ALBUM_ERROR = 'ALBUM_ERROR';
export const CANCION_ACTUAL = 'CANCION_ACTUAL';

export const OBTENER_VIDEOS = 'OBTENER_VIDEOS';
export const VIDEO_ERROR = 'VIDEO_ERROR';

export const OBTENER_LETRA = 'OBTENER_LETRA';
export const LETRA_ERROR = 'LETRA_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';